import{a as c,S as y,i as l}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();c.defaults.baseURL="https://pixabay.com/api/";const h="50190409-57f653f3b13017a76580224dc";function L(s){return c("",{params:{key:h,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}}).then(t=>t.data).catch(t=>{throw console.log(t),t})}const u=document.querySelector(".gallery"),b=new y(".gallery .gallery-link",{captionsData:"alt"});function S(s){const t=s.map(({webformatURL:o,largeImageURL:a,tags:e,likes:r,views:n,comments:g,downloads:p})=>`<li class="gallery-item">
            <a class="gallery-link" href="${a}">
                <img class="gallery-image" src="${o}" alt="${e}" />
            </a>
            <div class="image-info">
                <p><strong>Likes:</strong> ${r}</p>
                <p><strong>Views:</strong> ${n}</p>
                <p><strong>Comments:</strong> ${g}</p>
                <p><strong>Downloads:</strong> ${p}</p>
            </div>
        </li>`).join("");u.innerHTML=t,b.refresh()}function q(){u.innerHTML=""}const f=document.querySelector(".loader");function m(){f.classList.remove("hidden")}function d(){f.classList.add("hidden")}const i=document.querySelector(".form");i.querySelector('input[name="search-text"]');i.querySelector("button");document.querySelector(".loader");i.addEventListener("submit",v);function v(s){s.preventDefault(),q();const t=s.target.elements["search-text"].value.trim();if(t===""){l.warning({title:"Caution",message:"You forgot to type what you search"});return}m(),L(t).then(o=>{if(o.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}S(o.hits)}).catch(o=>{console.log(o),l.error({title:"Error",message:"Illegal operation"})}).finally(()=>{d(),i.reset()})}m();d();
//# sourceMappingURL=index.js.map
